fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: group

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_management:
    resource: "@SumoCodersFrameworkUserBundle/Controller/"
    type:     annotation
